# Generated by Django 4.1.4 on 2022-12-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactformmessage_alter_setting_aboutus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformmessage',
            old_name='subject',
            new_name='number',
        ),
    ]
